require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'mobile' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  target 'mobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#   use_flipper!
    use_flipper!({ 'Flipper' => '0.95.0' })
  post_install do |installer|
    installer.pods_project.targets.each do |target|
    flipper_post_install(installer)


    targets_to_ignore = %w(React yoga)

          if targets_to_ignore.include? target.name
            target.remove_from_project
          end

        end
      end

  permissions_path = '../node_modules/react-native-permissions/ios'

#   pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
#   pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
#   pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
#   pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
end

target 'mobile-tvOS' do
  # Pods for mobile-tvOS

  target 'mobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
